name: Bug Reports

description: |
  Report errors, crashes, or otherwise incorect behavior.

  Please note that we consider requests for additional functionality (e.g. adding new arguments to existing resources) to be feature requests.

labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        ## A note from the maintainers

        Thank you very much for taking the time to submit a bug report! Community reports to this repository are one of our primary means of feedback, so we greatly appreciate you taking the time to do so. With that in mind, we ask for a few considerations to help keep things running smoothly.

        ## Before submitting a bug report

        ### Terraform Core related issues

        Consider whether your issue may be related to Terraform Core, rather than the AWS Cloud Control Provider. In those cases, please [open an issue](https://github.com/hashicorp/terraform/issues/new/choose) in the Terraform Core repository instead.

        <details>
          <summary>Common Issues Related to Terraform Core</summary>

          - Issues with the [HashiCorp Configuration Language](https://www.terraform.io/docs/configuration/index.html)
          - Resource creation/deletion ordering issues
          - Issues related to Terraform's [state file](https://developer.hashicorp.com/terraform/language/state) or [state dackend](https://developer.hashicorp.com/terraform/language/settings/backends/configuration) issues (including the S3 backend)
          - [Provisioner](https://developer.hashicorp.com/terraform/language/resources/provisioners/syntax) or [Terraform Registry](https://registry.terraform.io/) issues
          - Issues that span across multiple providers
        </details>

        ### Search for similar reports

        Please [search the existing issues](https://github.com/hashicorp/terraform-provider-awscc/issues?q=is%3Aissue) to see if someone else has already reported the bug you experienced. This helps keep all relevant information in one place (including any potential workarounds).

        <details>
          <summary>Search Tips</summary>

          Searching for keywords such as error messages or resource names is often helpful in finding related issues.

          Including closed issues in your search helps locate community workarounds and fixes from the past, or point towards regressions.
        </details>

  - type: checkboxes
    id: acknowledge_search
    attributes:
      label: Prior Bug Reports
      options:
        - label: I searched the repository for similar issues
          required: true

  - type: markdown
    attributes:
      value: |
        ## Bug Form

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please provide a brief description of the bug that you encountered. We provide additional sections for configuration details, logging output, and any other notable details.

        Note: We provide a basic template that we find is often a good starting point for describing issues. Since bugs are all a bit different, we understand if you choose not to use it.
      value: |
        #### Expected Behavior

        <!--- Describe what you expected to happen here --->

        #### Actual Behavior

        <!--- Describe what actually happens here --->
    validations:
      required: true

  - type: textarea
    id: resources
    attributes:
      label: Affected Resources / Data Sources
      description: |
        Please list any resources or data sources that are affected by the bug. This list does not need to include any ancillary resources needed for reproductions.
      placeholder: |
        Example:
        - aws_iam_user
        - data.aws_iam_user
    validations:
      required: false

  - type: input
    id: core_version
    attributes:
      label: Terraform Core Version
      description: |
        Running `terraform --version` in an [initialized directory](https://developer.hashicorp.com/terraform/tutorials/cli/init) will output version information for Terraform and the AWS Provider.
      placeholder: x.y.z
    validations:
      required: false

  - type: input
    id: provider_version
    attributes:
      label: AWS Provider Version
      description: |
        Please note that for versions older than the [most recent](https://registry.terraform.io/providers/hashicorp/aws/latest) major version, we may ask that you upgrade to a later version to see if your issue has already been fixed. If you're unable to upgrade to the latest major version, we ask that you provide additional context below.
      placeholder: x.y.z
    validations:
      required: true

  - type: textarea
    id: unable_to_upgrade
    attributes:
      label: Context for older versions
      description: |
        Additional context for the usage of versions older than the latest major version helps reduce a bit of the initial back and forth, since we generally [don't backport fixes](https://hashicorp.github.io/terraform-provider-aws/faq/#once-a-major-release-is-published-will-new-features-and-fixes-be-backported-to-previous-versions).

        This could be as simple as 'organizational restrictions', and is optional.
      value: |
        n/a
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > For configurations or logs of more than just a few lines, it's preferred to either share a Gist link or zip the files and upload them.
        >
        > Terraform configurations or debug logs under 25MB may be [attached directly in the field](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files). Files larger than this should be uploaded to a file hosting service and a link shared.
        >
        > For your security you can also encrypt the files using our [GPG public key](https://keybase.io/hashicorp).

  - type: textarea
    id: configuration
    attributes:
      label: Terraform Configuration
      description: |
        Please paste, upload, or link to a file or Gist containing all Terraform configurations required to reproduce the bug.

        **Bug reports without a functional reproduction may be closed without investigation.**
      placeholder: |
        ```hcl
        # Code fences apply format that makes inline configurations easier to read.
        ```
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      placeholder: |
        Example:
        - Make a change
        - Run `terraform apply`
    validations:
      required: false

  - type: textarea
    id: logging
    attributes:
      label: Log Output
      description: |
        If possible, please paste, upload, or link to a file or Gist containing debug logs. If you're not able to supply logging, providing context here instead helps limit back and forth.

        For information on obtaining debug output, see the [Terraform documentation on debugging](https://www.terraform.io/docs/internals/debugging.html).
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: |
        A freeform field for context that might help the community or maintainers to investigate the bug. This might be links to documentation or similar bug reports, specifics about your environment that might be of note, etc.
    validations:
      required: false

  - type: checkboxes
    id: contributor
    attributes:
      label: Plan to Contribute
      description: |
        If you plan to implement a fix for this, check this box to let the maintainers and community know. You can update this later if you change your mind. If this would be your first contribution, refer to the [contribution guide](https://hashicorp.github.io/terraform-provider-aws/) for tips on getting started.
      options:
        - label: Check this box if you plan to contribute a fix
          required: false
