name: Bug Reports

description: |
  Report errors, crashes, or otherwise incorect behavior.

  Please note that we consider requests for additional functionality (e.g. adding new arguments to existing resources) to be feature requests.

labels:
  - bug

# Just shows what all is possible
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for raising a bug report!

        Community reports to this repository are one of our primary means of feedback, so we greatly appreciate it. With that in mind, we ask for a few considerations to help keep things running smoothly.

  - id: acknowledge_search
    type: checkboxes
    attributes:
      label: Search for similar reports
      description: |
        Before submitting a bug report, please [search](https://github.com/hashicorp/terraform-provider-awscc/issues?q=is%3Aissue) to see if your issue has already been reported. This helps to keep all relevant information in one place, including any potential workarounds.

        > [!TIP]
        > Searching for keywords such as error messages, resources names, or argument names is often helpful in finding related issues. Including closed issues in your search can help locate previous solutions from the community, or point towards regressions.

      options:
        - label: I have searched the repository for issues related to mine.
          required: true
        - label: I am reporting an issue that was previously reported (regressions, previously stale, etc.).
          required: false

  - id: acknowledge_core
    type: checkboxes
    attributes:
      label: Consider whether the issue is related to Terraform Core
      description: |
        Consider whether your issue may be related to Terraform Core, rather than the AWS Cloud Control Provider. In those cases, please [open an issue](https://github.com/hashicorp/terraform/issues/new/choose) in the Terraform Core repository instead. A few common examples of these types of issues may be found below.

        - Issues with the [HashiCorp Configuration Language](https://www.terraform.io/docs/configuration/index.html)
        - Resource creation/deletion ordering issues
        - Issues related to Terraform's [state file](https://developer.hashicorp.com/terraform/language/state) or [state dackend](https://developer.hashicorp.com/terraform/language/settings/backends/configuration) issues (including the S3 backend)
        - [Provisioner](https://developer.hashicorp.com/terraform/language/resources/provisioners/syntax) issues
        - [Registry](https://registry.terraform.io/) issues
        - Issues that span across multiple providers

      options:
        - label: My issue is not related to the scenarios described above.
          required: true

  - id: textarea
    type: textarea
    attributes:
      label: This is the textarea label
      description: This is what the description looks like
      placeholder: This is what the placeholder looks like
      value: |
        locals {
          this = "This should be formatted"
        }
      render: hcl
    validations:
      required: false

  - id: input
    type: input
    attributes:
      label: This is the input label
      description: This is what the description looks like
      placeholder: This is what the placeholder looks like
      value: This is what the value looks like
    validations:
      required: true

  - id: dropdown
    type: dropdown
    attributes:
      label: This is what the dropdown label looks like
      description: This is what the description looks like
      multiple: false
      options:
        - "No"
        - "Yes"
      default: 0
    validations:
      required: false

  - id: checkboxes
    type: checkboxes
    attributes:
      label: This is what the checkboxes label looks like
      description: |
        This is what the description looks like.

        I've added a couple of line breaks here to see if that works.

        **This should be bold if this accepts markdown**
      options:
        - label: This is the first option label
          required: false
        - label: This is a required option label
          required: true
