name: Bug Reports

description: |
  Report errors, crashes, or otherwise incorect behavior.

  Please note that we consider requests for additional functionality (e.g. adding new arguments to existing resources) to be feature requests.

labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for raising a bug report!
        ---

        Community reports to this repository are one of our primary means of feedback, so we greatly appreciate it. With that in mind, we ask for a few considerations to help keep things running smoothly.

        - Before submitting a bug report, please [search](https://github.com/hashicorp/terraform-provider-awscc/issues?q=is%3Aissue) to see if your issue has already been reported.

          > [!TIP]
          > Searching for keywords such as error messages, resources names, or argument names is often helpful in finding related issues. Including closed issues in your search can help locate previous solutions from the community, or point towards regressions.

        - Consider whether your issue may be related to Terraform Core, rather than the AWS Cloud Control Provider. In those cases, please [open an issue](https://github.com/hashicorp/terraform/issues/new/choose) in the Terraform Core repository instead. A few common examples of these types of issues may be found below.

          <details><summary>Terraform Core Examples</summary>

            - Testing to see how this renders
            - There doesn't seem to be anything online that gives a good idea of how
            - This will render out
            - Or if you should use HTML or markdown within the details tags

            <ul>
              <li>one</li>
              <li>two</li>
              <li>three</li>
              <li>four</li>
              <li>five</li>
            </ul>
          </details>
