name: Enhancement Request

description: |
  Request an enhancement (e.g. new arguments or attributes) to an existing resource, data source, or the provider itself.

labels:
  - enhancement

body:
  - type: markdown
    attributes:
      value: |
        ## A note from the maintainers

        This form is intended as a way to request additional functionality for existing resources, data sources, or the provider itself. This may include requests such as adding additional arguments or attributes enabled by upstream API changes, additional validation for arguments, etc.

        If the absense of the requested feature is causing unexpected behavior in the provider, the Bug Report form should be used. For entirely new resources, data sources, or services, please use the New Resource, Data Source, or AWS Service form.

        ### Search for similar requests

        Please [search the existing issues](https://github.com/hashicorp/terraform-provider-awscc/issues?q=is%3Aissue) to see if someone else has already opened a similar request. This helps keep all relevant information in one place (including any potential workarounds).

        Including closed issues in your search helps locate previous requests that may indicate why a particular feature doesn't currently exist.

        ## Enhancement Form

  - type: textarea
    id: affected
    attributes:
      label: Affected Resource(s) and/or Data Source(s)
      placeholder: |
        Example:
        - aws_iam_role
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please provide a brief description of the enhancement that you would like to see implemented.
    validations:
      required: true

  - type: textarea
    id: tf_config
    attributes:
      label: Potential Terraform Configuration
      description: |
        If this request was implemented, what might the Terraform configuration look like? A best guess is helpful, even if you're unsure of exactly what the end result will look like. This helps maintainers and the community better understand how you (someone who is in need of this feature) envisions it.
      placeholder: |
        ```hcl
        # Code fences with the 'hcl' key apply formatting that makes inline configuration more readable
        ```
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Where possible, please supply links to vendor documentation, other GitHub issues (open or closed) or pull requests that give additional context.

        [Information about referencing Github Issues](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests)
    validations:
      required: false

  - type: dropdown
    id: contributor
    attributes:
      label: Plan to Contribute
      multiple: false
      default: 0
      description: |
        If you plan to implement the feature, check this box to let the maintainers and community know. You can update this later if you change your mind. If this would be your first contribution, refer to the [contribution guide](https://hashicorp.github.io/terraform-provider-aws/) for tips on getting started.
      options:
        - "No"
        - "Yes"
    validations:
      required: false
