name: "🚀 Feature Request"
description: "I have a suggestion (and might want to implement myself 🙂)!"
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Community Note
      description: Please leave this note as is for the community
      value: |
        * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
        * Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
        * If you are interested in working on this issue or have submitted a pull request, please leave a comment
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Please leave a helpful description of the feature request here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: New or Affected Resource(s)
      description: Please list the new or affected resource(s) and/or data source(s).
    validations:
      required: true
  - type: textarea
    attributes:
      label: Potential Terraform Configuration
      description: |
        Copy-paste your Terraform configurations here. For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file. For security, you can also encrypt the files using our [GPG public key](https://keybase.io/hashicorp).

        [Information about code formatting](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).
    validations:
      required: true
  - type: textarea
    attributes:
      label: References
      description: |
        Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor documentation?

        [Information about referencing Github Issues](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests)
