name: "🚀 Feature Request"
description: "I have a suggestion (and might want to implement myself 🙂)!"
title: "[Feature Request]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: textarea
    attributes:
      label: Description
      description: Please leave a helpful description of the feature request here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: New or Affected Resource(s)
      description: Please list the new or affected resource(s) and/or data source(s).
      placeholder: "* aws_xxx"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Potential Terraform Configuration
      description: |
        Copy-paste your Terraform configurations here. For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file. For security, you can also encrypt the files using our [GPG public key](https://keybase.io/hashicorp).

        [Information about code formatting](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).
    validations:
      required: true
  - type: textarea
    attributes:
      label: References
      description: |
        Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor documentation?

        [Information about referencing Github Issues](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests)